/**
 * 将 NiuBot stable system context 同步到 Cursor workspace rules（.cursor/rules/*.mdc）。
 * 仅由 cursor backend 使用。
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const CURSOR_RULES_DIR = ".cursor/rules";
export const CURSOR_ENGINE_RULE_BASENAME = "niubot-engine.mdc";

/** @deprecated 已合并进 niubot-engine.mdc，仅用于清理旧文件 */
export const CURSOR_RECOVERY_RULE_BASENAME = "niubot-recovery.mdc";

export interface SyncCursorWorkspaceRulesResult {
  engineUpdated: boolean;
  rulesDir: string;
}

function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function buildMdc(alwaysApply: boolean, body: string, generatedBy: string): string {
  const header = [
    "---",
    `description: ${generatedBy}`,
    `alwaysApply: ${alwaysApply}`,
    "---",
    "",
  ].join("\n");
  return `${header}${body.trim()}\n`;
}

function readHashFile(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  try {
    return readFileSync(path, "utf8").trim() || undefined;
  } catch {
    return undefined;
  }
}

function writeIfChanged(filePath: string, hashPath: string, content: string): boolean {
  const nextHash = sha256(content);
  if (readHashFile(hashPath) === nextHash && existsSync(filePath)) {
    return false;
  }
  writeFileSync(filePath, content, "utf8");
  writeFileSync(hashPath, `${nextHash}\n`, "utf8");
  return true;
}

function removeLegacyRecoveryFiles(rulesDir: string): void {
  for (const basename of [
    CURSOR_RECOVERY_RULE_BASENAME,
    `${CURSOR_RECOVERY_RULE_BASENAME}.niubot-hash`,
  ]) {
    const filePath = join(rulesDir, basename);
    if (existsSync(filePath)) {
      unlinkSync(filePath);
    }
  }
}

/**
 * 将 stable context 写入 workspace/.cursor/rules/。
 * 使用旁路 .hash 文件避免无变化时反复写盘。
 */
export function syncCursorWorkspaceRules(
  workingDirectory: string,
  stableContext: string,
  options: { niubotVersion?: string } = {},
): SyncCursorWorkspaceRulesResult {
  const rulesDir = join(workingDirectory, CURSOR_RULES_DIR);
  mkdirSync(rulesDir, { recursive: true });
  removeLegacyRecoveryFiles(rulesDir);

  const version = options.niubotVersion ?? "unknown";
  const generatedBy = `AUTO-GENERATED by NiuBot ${version}; do not edit`;

  const enginePath = join(rulesDir, CURSOR_ENGINE_RULE_BASENAME);
  const engineHashPath = join(rulesDir, `${CURSOR_ENGINE_RULE_BASENAME}.niubot-hash`);
  const engineContent = buildMdc(true, stableContext, `${generatedBy} (engine stable context)`);
  const engineUpdated = writeIfChanged(enginePath, engineHashPath, engineContent);

  return { engineUpdated, rulesDir };
}
