/**
 * 将 NiuBot stable system context 同步到 Cursor workspace rules（.cursor/rules/*.mdc）。
 * 仅由 cursor backend 使用。
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const CURSOR_RULES_DIR = ".cursor/rules";
export const CURSOR_ENGINE_RULE_BASENAME = "niubot-engine.mdc";
export const CURSOR_RECOVERY_RULE_BASENAME = "niubot-recovery.mdc";

/** 固定恢复指引：动态 session 信息用 nbt 按需拉取 */
export const CURSOR_CONTEXT_RECOVERY_RULE_BODY = `你是通过 NiuBot 在远程 IM 里与用户对话的 Bot，不是普通本地终端。

上下文被压缩或不确定时，不要猜。用 shell 运行以下命令恢复：

- 引擎系统规则：\`nbt system-rules\`
- 当前场景 / 用户 / 记忆（等同 session profile）：\`nbt whoami\`
- 活跃任务：\`nbt task list\`，再读对应 task README
- 最近消息：\`nbt messages list\`
- 历史 session：\`nbt sessions list\` / \`nbt sessions search\` / \`nbt sessions get\`
- 项目规则原文：读取 workspace 的 \`AGENTS.md\`

不要把 compact 摘要当成原文。`;

export interface SyncCursorWorkspaceRulesResult {
  engineUpdated: boolean;
  recoveryUpdated: boolean;
  rulesDir: string;
}

function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function buildMdc(alwaysApply: boolean, body: string, generatedBy: string): string {
  const header = [
    "---",
    `description: ${generatedBy}`,
    `alwaysApply: ${alwaysApply}`,
    "---",
    "",
  ].join("\n");
  return `${header}${body.trim()}\n`;
}

function readHashFile(path: string): string | undefined {
  if (!existsSync(path)) return undefined;
  try {
    return readFileSync(path, "utf8").trim() || undefined;
  } catch {
    return undefined;
  }
}

function writeIfChanged(filePath: string, hashPath: string, content: string): boolean {
  const nextHash = sha256(content);
  if (readHashFile(hashPath) === nextHash && existsSync(filePath)) {
    return false;
  }
  writeFileSync(filePath, content, "utf8");
  writeFileSync(hashPath, `${nextHash}\n`, "utf8");
  return true;
}

/**
 * 将 stable context 写入 workspace/.cursor/rules/。
 * 使用旁路 .hash 文件避免无变化时反复写盘。
 */
export function syncCursorWorkspaceRules(
  workingDirectory: string,
  stableContext: string,
  options: { niubotVersion?: string } = {},
): SyncCursorWorkspaceRulesResult {
  const rulesDir = join(workingDirectory, CURSOR_RULES_DIR);
  mkdirSync(rulesDir, { recursive: true });

  const version = options.niubotVersion ?? "unknown";
  const generatedBy = `AUTO-GENERATED by NiuBot ${version}; do not edit`;

  const enginePath = join(rulesDir, CURSOR_ENGINE_RULE_BASENAME);
  const engineHashPath = join(rulesDir, `${CURSOR_ENGINE_RULE_BASENAME}.niubot-hash`);
  const engineContent = buildMdc(true, stableContext, `${generatedBy} (engine stable context)`);
  const engineUpdated = writeIfChanged(enginePath, engineHashPath, engineContent);

  const recoveryPath = join(rulesDir, CURSOR_RECOVERY_RULE_BASENAME);
  const recoveryHashPath = join(rulesDir, `${CURSOR_RECOVERY_RULE_BASENAME}.niubot-hash`);
  const recoveryContent = buildMdc(true, CURSOR_CONTEXT_RECOVERY_RULE_BODY, `${generatedBy} (context recovery)`);
  const recoveryUpdated = writeIfChanged(recoveryPath, recoveryHashPath, recoveryContent);

  return { engineUpdated, recoveryUpdated, rulesDir };
}
