import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  CURSOR_ENGINE_RULE_BASENAME,
  CURSOR_RECOVERY_RULE_BASENAME,
  CURSOR_RULES_DIR,
  syncCursorWorkspaceRules,
} from "./cursor-workspace-rules.js";

describe("syncCursorWorkspaceRules", () => {
  const tempDirs: string[] = [];

  afterEach(() => {
    for (const dir of tempDirs.splice(0)) {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("writes engine rule under .cursor/rules and removes legacy recovery rule", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);
    const stable = "<niubot-system-rules>\nengine body\n</niubot-system-rules>";
    const rulesDir = join(dir, CURSOR_RULES_DIR);

    const result = syncCursorWorkspaceRules(dir, stable, { niubotVersion: "0.1.89" });

    expect(result.rulesDir).toBe(rulesDir);
    expect(result.engineUpdated).toBe(true);

    const enginePath = join(rulesDir, CURSOR_ENGINE_RULE_BASENAME);
    const recoveryPath = join(rulesDir, CURSOR_RECOVERY_RULE_BASENAME);
    expect(existsSync(enginePath)).toBe(true);
    expect(existsSync(recoveryPath)).toBe(false);

    const engine = readFileSync(enginePath, "utf8");
    expect(engine).toContain("alwaysApply: true");
    expect(engine).toContain("engine body");
    expect(engine).toContain("AUTO-GENERATED by NiuBot 0.1.89");
  });

  it("skips writes when stable context hash is unchanged", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);
    const stable = "stable-v1";

    const first = syncCursorWorkspaceRules(dir, stable);
    const second = syncCursorWorkspaceRules(dir, stable);

    expect(first.engineUpdated).toBe(true);
    expect(second.engineUpdated).toBe(false);
  });

  it("updates engine rule when stable context changes", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);

    syncCursorWorkspaceRules(dir, "stable-v1");
    const result = syncCursorWorkspaceRules(dir, "stable-v2");

    expect(result.engineUpdated).toBe(true);
    const engine = readFileSync(join(dir, CURSOR_RULES_DIR, CURSOR_ENGINE_RULE_BASENAME), "utf8");
    expect(engine).toContain("stable-v2");
  });

  it("deletes legacy recovery rule files on sync", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);
    const rulesDir = join(dir, CURSOR_RULES_DIR);

    syncCursorWorkspaceRules(dir, "stable-v1");
    const recoveryPath = join(rulesDir, CURSOR_RECOVERY_RULE_BASENAME);
    const recoveryHashPath = join(rulesDir, `${CURSOR_RECOVERY_RULE_BASENAME}.niubot-hash`);
    expect(existsSync(recoveryPath)).toBe(false);
    expect(existsSync(recoveryHashPath)).toBe(false);

    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(recoveryPath, "legacy", "utf8");
    writeFileSync(recoveryHashPath, "legacy-hash\n", "utf8");

    syncCursorWorkspaceRules(dir, "stable-v1");
    expect(existsSync(recoveryPath)).toBe(false);
    expect(existsSync(recoveryHashPath)).toBe(false);
  });
});
