import { mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  CURSOR_ENGINE_RULE_BASENAME,
  CURSOR_RECOVERY_RULE_BASENAME,
  CURSOR_RULES_DIR,
  syncCursorWorkspaceRules,
} from "./cursor-workspace-rules.js";

describe("syncCursorWorkspaceRules", () => {
  const tempDirs: string[] = [];

  afterEach(() => {
    for (const dir of tempDirs.splice(0)) {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("writes engine and recovery rules under .cursor/rules", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);
    const stable = "<niubot-system-rules>\nengine body\n</niubot-system-rules>";

    const result = syncCursorWorkspaceRules(dir, stable, { niubotVersion: "0.1.89" });

    const rulesDir = join(dir, CURSOR_RULES_DIR);
    expect(result.rulesDir).toBe(rulesDir);
    expect(result.engineUpdated).toBe(true);
    expect(result.recoveryUpdated).toBe(true);

    const enginePath = join(rulesDir, CURSOR_ENGINE_RULE_BASENAME);
    const recoveryPath = join(rulesDir, CURSOR_RECOVERY_RULE_BASENAME);
    expect(existsSync(enginePath)).toBe(true);
    expect(existsSync(recoveryPath)).toBe(true);

    const engine = readFileSync(enginePath, "utf8");
    expect(engine).toContain("alwaysApply: true");
    expect(engine).toContain("engine body");
    expect(engine).toContain("AUTO-GENERATED by NiuBot 0.1.89");

    const recovery = readFileSync(recoveryPath, "utf8");
    expect(recovery).toContain("nbt whoami");
    expect(recovery).toContain("nbt system-rules");
  });

  it("skips writes when stable context hash is unchanged", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);
    const stable = "stable-v1";

    const first = syncCursorWorkspaceRules(dir, stable);
    const second = syncCursorWorkspaceRules(dir, stable);

    expect(first.engineUpdated).toBe(true);
    expect(second.engineUpdated).toBe(false);
    expect(second.recoveryUpdated).toBe(false);
  });

  it("updates engine rule when stable context changes", () => {
    const dir = mkdtempSync(join(tmpdir(), "niubot-cursor-rules-"));
    tempDirs.push(dir);

    syncCursorWorkspaceRules(dir, "stable-v1");
    const result = syncCursorWorkspaceRules(dir, "stable-v2");

    expect(result.engineUpdated).toBe(true);
    const engine = readFileSync(join(dir, CURSOR_RULES_DIR, CURSOR_ENGINE_RULE_BASENAME), "utf8");
    expect(engine).toContain("stable-v2");
  });
});
